import Foundation
import ScriptingBridge

/// Real ScriptingBridge implementation. The generated `CaptureOneApplication`,
/// `CaptureOneDocument`, `CaptureOneVariant`, `CaptureOneImage` types come from
/// CaptureOne.h (generated by `sdp` from the installed Capture One scripting dictionary).
public final class CaptureOneBridge: CaptureOneBridging {
    private let bundleId = "com.captureone.captureone16"

    public init() {}

    public func readSelection() throws -> [VariantInfo] {
        guard let app: CaptureOneApplication = SBApplication(bundleIdentifier: bundleId) else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        guard app.isRunning else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        guard let doc = app.currentDocument else {
            throw CaptureOneBridgeError.noDocumentOpen
        }
        let allVariants: [CaptureOneVariant] = (doc.variants?() as? [CaptureOneVariant]) ?? []
        let selected = allVariants.filter { $0.selected }
        return selected.compactMap { v -> VariantInfo? in
            guard let parent = v.parentImage, let path = parent.path else { return nil }
            let name = (path as NSString).lastPathComponent
            let date = parent.EXIFCaptureDate
            return VariantInfo(filePath: path, filename: name, currentExifDate: date)
        }
    }

    public func reloadMetadata(for paths: [String]) throws {
        guard let app: CaptureOneApplication = SBApplication(bundleIdentifier: bundleId),
              app.isRunning,
              let doc = app.currentDocument else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        let allVariants: [CaptureOneVariant] = (doc.variants?() as? [CaptureOneVariant]) ?? []
        let pathSet = Set(paths)
        for v in allVariants where pathSet.contains(v.parentImage?.path ?? "") {
            v.reloadMetadata?()
        }
    }
}
