import Foundation
import ScriptingBridge
import AppKit

/// Real ScriptingBridge implementation. The generated `CaptureOneApplication`,
/// `CaptureOneDocument`, `CaptureOneVariant`, `CaptureOneImage` types come from
/// CaptureOne.h (generated by `sdp` from the installed Capture One scripting dictionary).
/// ScriptingBridge fabricates these classes at runtime, so we type the SBApplication via
/// `unsafeBitCast` and use KVC (`value(forKey:)` / `perform(Selector(...))`) for property
/// and method access — typed casts produce undefined-symbol errors at link time.
public final class CaptureOneBridge: CaptureOneBridging {
    private let bundleId = "com.captureone.captureone16"

    public init() {}

    public func readSelection() throws -> [VariantInfo] {
        try ensureAutomationPermission()
        let app = try connect()
        guard let doc = app.currentDocument else {
            throw CaptureOneBridgeError.noDocumentOpen
        }
        let variantArray = doc.variants() as NSArray
        let selected = variantArray.compactMap { $0 as? SBObject }.filter { ($0.value(forKey: "selected") as? Bool) == true }
        return selected.compactMap { obj -> VariantInfo? in
            let v = obj as AnyObject
            guard let parent = v.value(forKey: "parentImage") as? SBObject else { return nil }
            guard let path = parent.value(forKey: "path") as? String else { return nil }
            let name = (path as NSString).lastPathComponent
            let date = parent.value(forKey: "EXIFCaptureDate") as? Date
            return VariantInfo(filePath: path, filename: name, currentExifDate: date)
        }
    }

    public func reloadMetadata(for paths: [String]) throws {
        try ensureAutomationPermission()
        let app = try connect()
        guard let doc = app.currentDocument else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        let variantArray = doc.variants() as NSArray
        let pathSet = Set(paths)
        for obj in variantArray {
            let v = obj as AnyObject
            if let parentImage = v.value(forKey: "parentImage") as? SBObject,
               let path = parentImage.value(forKey: "path") as? String,
               pathSet.contains(path) {
                v.perform(Selector(("reloadMetadata")))
            }
        }
    }

    // MARK: - Private

    private func connect() throws -> CaptureOneApplication {
        guard let rawApp = SBApplication(bundleIdentifier: bundleId) else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        let app = unsafeBitCast(rawApp, to: CaptureOneApplication.self)
        guard app.isRunning else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        return app
    }

    /// Triggers the system Automation TCC prompt on first call and maps any subsequent
    /// denial (`errAEEventNotPermitted`) to `automationPermissionDenied`. Without this,
    /// a denied app silently surfaces SBApplication failures as `bridgeFailure`, and
    /// the dedicated permission-denied UI never appears.
    private func ensureAutomationPermission() throws {
        guard let bundleData = bundleId.data(using: .utf8) else { return }
        var address = AEAddressDesc()
        let createStatus: OSErr = bundleData.withUnsafeBytes { ptr -> OSErr in
            guard let base = ptr.baseAddress else { return -1 }
            return AECreateDesc(DescType(typeApplicationBundleID), base, bundleData.count, &address)
        }
        guard createStatus == 0 else { return }
        defer { AEDisposeDesc(&address) }

        let result = AEDeterminePermissionToAutomateTarget(
            &address,
            AEEventClass(typeWildCard),
            AEEventID(typeWildCard),
            true   // prompt the user the first time
        )
        switch Int(result) {
        case Int(noErr):
            return
        case Int(errAEEventNotPermitted):
            throw CaptureOneBridgeError.automationPermissionDenied
        case Int(procNotFound):
            throw CaptureOneBridgeError.captureOneNotRunning
        default:
            throw CaptureOneBridgeError.bridgeFailure(
                "AEDeterminePermissionToAutomateTarget returned \(result)"
            )
        }
    }
}
