import Foundation
import ScriptingBridge

/// Real ScriptingBridge implementation. The generated `CaptureOneApplication`,
/// `CaptureOneDocument`, `CaptureOneVariant`, `CaptureOneImage` types come from
/// CaptureOne.h (generated by `sdp` from the installed Capture One scripting dictionary).
public final class CaptureOneBridge: CaptureOneBridging {
    private let bundleId = "com.captureone.captureone16"

    public init() {}

    public func readSelection() throws -> [VariantInfo] {
        guard let rawApp = SBApplication(bundleIdentifier: bundleId) else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        let app = unsafeBitCast(rawApp, to: CaptureOneApplication.self)
        guard app.isRunning else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        guard let doc = app.currentDocument else {
            throw CaptureOneBridgeError.noDocumentOpen
        }
        let variantArray = doc.variants() as NSArray
        let selected = variantArray.compactMap { $0 as? SBObject }.filter { ($0.value(forKey: "selected") as? Bool) == true }
        return selected.compactMap { obj -> VariantInfo? in
            let v = obj as AnyObject
            guard let parent = v.value(forKey: "parentImage") as? SBObject else { return nil }
            guard let path = parent.value(forKey: "path") as? String else { return nil }
            let name = (path as NSString).lastPathComponent
            let date = parent.value(forKey: "EXIFCaptureDate") as? Date
            return VariantInfo(filePath: path, filename: name, currentExifDate: date)
        }
    }

    public func reloadMetadata(for paths: [String]) throws {
        guard let rawApp = SBApplication(bundleIdentifier: bundleId) else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        let app = unsafeBitCast(rawApp, to: CaptureOneApplication.self)
        guard app.isRunning,
              let doc = app.currentDocument else {
            throw CaptureOneBridgeError.captureOneNotRunning
        }
        let variantArray = doc.variants() as NSArray
        let pathSet = Set(paths)
        for obj in variantArray {
            let v = obj as AnyObject
            if let parentImage = v.value(forKey: "parentImage") as? SBObject,
               let path = parentImage.value(forKey: "path") as? String,
               pathSet.contains(path) {
                v.perform(Selector(("reloadMetadata")))
            }
        }
    }
}
